apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubclient-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubclient
    spec:
      containers:
      - name: kubclient
        image: cluster.kube.com:30500/kubclient:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
