apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: serviceone-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceone
    spec:
      containers:
      - name: serviceone
        image: cluster.kube.com:30500/serviceone:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
