kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-system-kube-registry-pv
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: registry
  iscsi:
    targetPortal: 192.168.99.1
    iqn: iqn.2003-01.org.linux-iscsi.predator.x8664:sn.14bb0d0b0463
    lun: 0
    fsType: 'ext4'
    readOnly: false
